import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ToastContextProvider from "../contexts/ToastContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rent House Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ToastContextProvider>
        <body className={inter.className}>
          <ToastContainer />
          {children}
        </body>
      </ToastContextProvider>
    </html>
  );
}
